// <auto-generated />
using System;
using LibraryWithWebApiConsole.Store;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Assignment_6_LibraryWithWebApiConsole.Migrations
{
    [DbContext(typeof(LibraryContext))]
    [Migration("20191008140721_AddedAllTable")]
    partial class AddedAllTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LibraryWithWebApi.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Author");

                    b.Property<string>("BarCode");

                    b.Property<int>("CopyCount");

                    b.Property<string>("Edition");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("LibraryWithWebApi.Models.IssueBook", b =>
                {
                    b.Property<int>("StudentId");

                    b.Property<int>("bookId");

                    b.Property<string>("BookBarCode");

                    b.Property<DateTime>("IssueDate");

                    b.HasKey("StudentId", "bookId");

                    b.HasIndex("bookId");

                    b.ToTable("IssueBooks");
                });

            modelBuilder.Entity("LibraryWithWebApi.Models.ReturnBook", b =>
                {
                    b.Property<int>("StudentId");

                    b.Property<int>("bookId");

                    b.Property<string>("BookBarCode");

                    b.Property<DateTime>("ReturnDate");

                    b.HasKey("StudentId", "bookId");

                    b.HasIndex("bookId");

                    b.ToTable("ReturnBooks");
                });

            modelBuilder.Entity("LibraryWithWebApi.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("FineAmount");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("LibraryWithWebApi.Models.IssueBook", b =>
                {
                    b.HasOne("LibraryWithWebApi.Models.Student", "Student")
                        .WithMany("BookIssues")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("LibraryWithWebApi.Models.Book", "book")
                        .WithMany()
                        .HasForeignKey("bookId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("LibraryWithWebApi.Models.ReturnBook", b =>
                {
                    b.HasOne("LibraryWithWebApi.Models.Student", "Student")
                        .WithMany("BookReturns")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("LibraryWithWebApi.Models.Book", "book")
                        .WithMany()
                        .HasForeignKey("bookId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
